### ISSUE TITLE
ReferenceFrame.getTransformToParent(RigidBodyTransform transformToPack) does not work correctly for frames with unchanging transforms

### ISSUE THREAD

**Issue by jespersmith** [ihmcrobotics/euclid#12]
ReferenceFrame.getTransformToParent() returns a  copy of transformToParent, while ReferenceFrame.getTransformToParent(RigidBodyTransform transformToPack) calls updateTransformToParent(transformToPack) 

ReferenceFrames with unchanging transform to parent have an empty updateTransformToParent and set transformToParent in the constructor. Hence the result does not match ReferenceFrame.getTransformToParent()

**Comment by SylvainBertrand** [comment]
Alright should be fix in Euclid v0.7.9.2

**Comment by SylvainBertrand** [comment]
I'm closing this issue as it has been fixed.
