### ISSUE TITLE
ReferenceFrameTools.clearWorldFrameTree() should reset indices

### ISSUE THREAD

**Issue by jespersmith** [ihmcrobotics/euclid#32]
To make it possible to reset the state of the controller to start, ReferenceFrameTools.clearWorldFrameTree() should set the framesAddedToTree variable in ReferenceFrame worldframe to 0.

**Comment by SylvainBertrand** [comment]
Oh yeah indeed, I'll look into that

**Comment by SylvainBertrand** [comment]
This issue is resolved with the 0.15.2 release.
