### ISSUE TITLE
How to get the pose-transform between poses

### ISSUE THREAD

**Issue by beetleskin** [ihmcrobotics/euclid#45]
Hi, I'm looking into euclid and like it - it seems there are not that many robotics-centric spatial-math libs out there for java!

For my use-case, I often have to transform a point from one frame/pose to another frame/pose. For this, I'm used to functions like
`poseA.between(poseB)` giving me the transform between two poses and `pose.inverse()`  giving me the inverse of the pose's transform - where pose would be in 2D or 3D. How would I do that in euclid?

For some context, I'm coming from the GTSAM way of pose calculus: https://github.com/devbharat/gtsam/blob/master/gtsam/geometry/Pose3.h

Thanks!

**Comment by beetleskin** [comment]
It is! But I got a list of thousand poses that define some frames. I don't want to define a fill transform-chain via parent-child relations and the ReferenceFrame. I rather have Poses that define some transforms that I want to apply to points or lines. It seems there is no interface to do that directly `(Pose3D::transformPoint(somePoint3D))` - I have to convert the Pose3D to a `RigidTransform` first? Or did I miss a shortcut?

**Comment by SylvainBertrand** [comment]
Yeah indeed, the `Pose3D` as it is currently implemented is more about considering it as a geometry object and not as a transform. I can't be used at the moment to transform other geometries.
`RigidBodyTransform` will be a necessary intermediate :/ can you use the `RigidBodyTransform` directly?

**Comment by beetleskin** [comment]
That would also work I guess. I just found it nicer to describe Poses as .. Poses in the first place. Any thoughts about a zero-copy interface between the two?

I'll close, no issue here and questions answered. Thanks! :) And again thanks for closing a huge gap in Java. And maybe, sorry for advertising again, get some inspiration from the [GTSAM spatial APIs](https://github.com/devbharat/gtsam/blob/master/gtsam/geometry/Pose3.h), its really great for robotics applications of any kind.

**Comment by SylvainBertrand** [comment]
So could actually just instantiate a `RigidBodyTransformBasics` directly linking to the rotation and position of the pose. That would essentially be a way to do a zero-copy interface

**Comment by SylvainBertrand** [comment]
I had heard of GTSAM in the past, I'll take a look at it. Thanks fo the link
