### ISSUE TITLE
Documentation of `FrameShape3DReadOnly#getPose` Incorrect

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/euclid#53]
The documenation of us.ihmc.euclid.referenceFrame.interfaces.FrameShape3DReadOnly#getPose
reads 
> Returns {@code null} as this shape is not defined by a pose.

 but many implementations actually do have a pose and don't return null

**Comment by SylvainBertrand** [comment]
Fair, I think this might be a copy-paste booboo

**Comment by SylvainBertrand** [comment]
That'll be fixed in the next release
