### ISSUE TITLE
`RigidBodyTransformReadOnly` lacks getters to `M00`, `M01`, etc.

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/euclid#58]
Can the getters to the 4x4 elements become part of the ReadOnly interface?

**Comment by SylvainBertrand** [comment]
The issue here is that the rotation part of the `RigidBodyTransformReadOnly` is a `Orientation3DReadOnly`, so not necessarily a `RotationMatrix`. This allows `Pose3DReadOnly` to be a transform.

**Comment by calvertdw** [comment]
Oh, dang. This is mostly for packing 4x4 matrices to get copied into GPU kernels. Probably could keep a `RotationMatrix` handy and set if from the `Orientation3DReadOnly` in `RigidBodyTransformReadOnly` and use that.
