### ISSUE TITLE
`FramePose3DBasics` should override `FixedFramePose3DBasics#set(ReferenceFrame, Pose3DReadOnly)`

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/euclid#59]
`FixedFramePose3DBasics#set(ReferenceFrame, Pose3DReadOnly)` throws an exception if the `referenceFrame` passed in is different, which makes sense for a fixed frame object. But very often, what you've actually got is a non-fixed frame pose, and the `set(ReferenceFrame, Pose3DReadOnly)` could be more helpful by figuring it out instead. This is pretty much just a `setIncludingFrame` and `changeFrame` back to the original.

**Comment by SylvainBertrand** [comment]
Ok what you're describing is `setMatchingFrame(...)` and yeah there are quite a few missing for that class. I'll add them

**Comment by SylvainBertrand** [comment]
That's on develop, will be in the next release

**Comment by calvertdw** [comment]
Thanks!
